QUOTE The working directory must DIRECTLY contain this Batch300-50.run, Stats_CI.run and Datasets1,2 etc ;
QUOTE Trees rooted using single outgroup due to TNT limitations, may need to re-root later;
QUOTE Log file is a text file showing tree statistics for the MP tree(s) - usually single tree in GM - first tree is called Tree 0;
QUOTE Adjusted homoplasy is based on default K=3, use PIWE = K to change;
QUOTE Dataset1_ancestralConfigs.tps is a tps file has a table of ancestral configurations;
QUOTE Dataset1_ancestralConfigs.txt is a text file that has a table of ancestral configurations at each node - the nodes labelled in Dataset1_MP_Tree_nodelabels.trees ;
QUOTE Dataset1_MP_TNTformat.tree is a TNT readable tree;
QUOTE Dataset1_MP_Tree_nodelabels.trees has ancestral nodes numbered, opens in most nexus tree viewers ;
QUOTE Dataset1_MP_Tree1_BranchLengths.tre is a nexus file with branch lengths as annotations, opens in SOME nexus tree viewers eg FigTree1.4.4 ;


LOG	Dataset1.log
PROC Dataset1.tnt;
LMARK noconfsample;
LMARK options;
TAXNAME= ;
OUTGROUP Rhyncholestes_raphanurus ;
HOLD	300;	MULT=REPLIC	50;	BBREAK=TBR;	
LENGTH; FIT;
LMARK lscores ;
PROC Stats_CI.run;
LOG /;
CLBUFFER *;
CLBUFFER;
LOG Dataset1_ancestralConfigs.txt; 
LMARK showhtu; LMARK map; 
LOG/;
EXPORT | Dataset1_ancestralConfigs.tps 0 0 ;
TSAVE * Dataset1_MP_TNTformat.tree ; SAVE 0; TSAVE /;
NAKED-; TTAG=; TPLOT 0;
EXPORT	-	Dataset1_MP_nexus_with_NodeLabels.tree	;	
TTAG-; TTAG=; BLENGTH * 0 ;
EXPORT > Dataset1_MP_nexus_with_BranchLengths.tree ;
TTAG -;



LOG	Dataset2.log
PROC Dataset2.tnt;
LMARK noconfsample;
LMARK options;
TAXNAME= ;
OUTGROUP Rhyncholestes_raphanurus ;
HOLD	300;	MULT=REPLIC	50;	BBREAK=TBR;	
LENGTH; FIT;
LMARK lscores ;
PROC Stats_CI.run;
LOG /;
CLBUFFER *;
CLBUFFER;
LOG Dataset2_ancestralConfigs.txt; 
LMARK showhtu; LMARK map; 
LOG/;
EXPORT | Dataset2_ancestralConfigs.tps 0 0 ;
TSAVE * Dataset2_MP_TNTformat.tree ; SAVE 0; TSAVE /;
NAKED-; TTAG=; TPLOT 0;
EXPORT	-	Dataset2_MP_nexus_with_NodeLabels.tree	;	
TTAG-; TTAG=; BLENGTH * 0 ;
EXPORT > Dataset2_MP_nexus_with_BranchLengths.tree ;
TTAG -;


PROC /;


